// components/vc-switch/demo/simple.vue
<script>
import VcSwitch from '../index';
import '../assets/index.less';

export default {
  data () {
    return {
      disabled: false,
    };
  },
  methods: {
    toggle () {
      this.disabled = !this.disabled;
    },
    onChange (value) {
      console.log(`switch checked: ${value}`); // eslint-disable-line
    },
  },
  render () {
    return (
      <div style='margin: 20px'>
        <VcSwitch
          onChange={this.onChange}
          disabled={this.disabled}
          checkedChildren={'开'}
          unCheckedChildren={'关'}
        />
        <div style='margin-top: 20px'>
          <button onClick={this.toggle}>toggle disabled</button>
        </div>
      </div>
    );
  },
};
</script>

// components/vc-input-number/demo/simple.jsx
import InputNumber from '../src/index';
import '../assets/index.less';

export default {
  data() {
    return {
      disabled: false,
      readOnly: false,
      value: 5,
    };
  },
  methods: {
    onChange(value) {
      console.log('onChange:', value);
      this.value = value;
    },
    toggleDisabled() {
      this.disabled = !this.disabled;
    },
    toggleReadOnly() {
      this.readOnly = !this.readOnly;
    },
  },
  render() {
    return (
      <div style="margin: 10px;">
        <InputNumber
          min={-8}
          max={10}
          value={this.value}
          onChange={this.onChange}
          style="width: 100px"
          readOnly={this.readOnly}
          disabled={this.disabled}
        />
        <p style="padding:10px 0">
          <button onClick={this.toggleDisabled}>toggle Disabled</button>
          <button onClick={this.toggleReadOnly}>toggle readOnly</button>
        </p>
      </div>
    );
  },
};
